#!/usr/bin/env python3
"""
Install this plugin's subagents into Codex as native TOML custom agents.

Codex runs custom agents natively, but its plugin-install flow does not yet
pick agents up from a plugin manifest (skills/commands/MCP it does — via
.codex-plugin/plugin.json). This script fills that one gap, the same way
compound-engineering's converter and agent-scripts/gen-subagents.py do.

Single source of truth: the plugin's `agents/*.md` (Claude-Code-flavoured —
YAML frontmatter + body-as-system-prompt). Claude Code reads those directly
when the plugin is installed; Codex gets a *generated* TOML copy here, because
the formats genuinely differ (Codex puts the prompt in a field, uses a
sandbox_mode instead of a tools list).

Pruning is MANIFEST-BASED: only files this script previously wrote (tracked in
.agent-manifest in the target dir) are ever removed. Hand-authored TOML that
happens to share a name is never touched.

Usage:
  python3 scripts/gen-codex-agents.py [--codex-agents-dir DIR] [--dry-run] [--quiet]

Default target: ~/.codex/agents/distribution-engineering/
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

PLUGIN_NAME = "distribution-engineering"
MANIFEST = ".agent-manifest"

# Claude tool names that imply no filesystem writes. If an agent's `tools:` list
# is a subset of these, the Codex agent runs read-only; otherwise workspace-write.
READ_ONLY_TOOLS = {"Read", "Grep", "Glob", "WebSearch", "WebFetch", "NotebookRead"}


def parse_agent(path: Path) -> dict:
    """Minimal frontmatter parser for the format we own (restricted YAML)."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError(f"{path.name}: missing YAML frontmatter")
    _, fm, body = text.split("---", 2)
    meta: dict[str, str] = {}
    for line in fm.strip().splitlines():
        line = line.rstrip()
        if not line or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        meta[key.strip()] = val.strip()
    tools_raw = meta.get("tools", "").strip()
    tools = [t.strip() for t in tools_raw.split(",") if t.strip()] if tools_raw else []
    return {
        "name": meta.get("name") or path.stem,
        "description": meta.get("description", "").strip(),
        "model": meta.get("model", "inherit").strip(),
        "tools": tools,
        "body": body.strip() + "\n",
    }


def sandbox_mode(tools: list[str]) -> str | None:
    """read-only if every listed tool is non-mutating; else workspace-write.
    None (omit) when no tools are declared, so Codex applies its own default."""
    if not tools:
        return None
    return "read-only" if set(tools).issubset(READ_ONLY_TOOLS) else "workspace-write"


def _toml_basic(s: str) -> str:
    # TOML basic string: escape backslashes then quotes. Escaping every " also
    # prevents a stray triple-quote run from closing a multiline string early.
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_codex(a: dict) -> str:
    lines = [
        f'name = "{_toml_basic(a["name"])}"',
        f'description = "{_toml_basic(a["description"])}"',
    ]
    sb = sandbox_mode(a["tools"])
    if sb:
        lines.append(f'sandbox_mode = "{sb}"')
    if a["model"] and a["model"] != "inherit":  # 'inherit' => omit, use parent model
        lines.append(f'model = "{_toml_basic(a["model"])}"')
    lines.append(f'developer_instructions = """\n{_toml_basic(a["body"])}"""')
    return "\n".join(lines) + "\n"


def sync(agents: list[dict], out_dir: Path, dry_run: bool, quiet: bool) -> int:
    def say(msg: str) -> None:
        if not quiet:
            print(f"  {msg}")

    print(f"== Distribution Engineering subagents -> Codex ({out_dir}) ==")
    wanted = {f"{a['name']}.toml": emit_codex(a) for a in agents}

    manifest_path = out_dir / MANIFEST
    prev = set()
    if manifest_path.exists():
        prev = {ln.strip() for ln in manifest_path.read_text().splitlines() if ln.strip()}

    for stale in sorted(prev - set(wanted)):
        p = out_dir / stale
        if p.exists():
            say(f"prune {stale}")
            if not dry_run:
                p.unlink()

    if not dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for fname, content in sorted(wanted.items()):
        dest = out_dir / fname
        # Never clobber a file we didn't generate.
        if dest.exists() and fname not in prev:
            print(f"  WARNING: {dest} exists and was not generated by this plugin "
                  f"— not overwriting.", file=sys.stderr)
            continue
        say(f"{'update' if dest.exists() else 'create'} {fname}")
        if not dry_run:
            dest.write_text(content, encoding="utf-8")
        written.append(fname)

    if not dry_run and written:
        manifest_path.write_text("\n".join(sorted(written)) + "\n", encoding="utf-8")
    print(f"   {len(written)} agent(s) {'would be ' if dry_run else ''}installed.")
    return 0


def main() -> int:
    plugin_root = Path(__file__).resolve().parent.parent
    home = Path(os.path.expanduser("~"))
    ap = argparse.ArgumentParser(description="Install plugin subagents into Codex as TOML.")
    ap.add_argument("--codex-agents-dir", type=Path,
                    default=home / ".codex" / "agents" / PLUGIN_NAME)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    src = plugin_root / "agents"
    if not src.is_dir():
        print(f"No {src} — nothing to generate.")
        return 0

    agents = []
    for path in sorted(src.glob("*.md")):
        try:
            agents.append(parse_agent(path))
        except ValueError as e:
            print(f"  SKIP {path.name}: {e}", file=sys.stderr)
    if not agents:
        print("No agents found.")
        return 0

    return sync(agents, args.codex_agents_dir, args.dry_run, args.quiet)


if __name__ == "__main__":
    raise SystemExit(main())
